apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-root
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1" # Root app - discovers operators before they deploy
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  source:
    repoURL: https://github.com/morheus9/gitops-cloudnativePG
    targetRevision: HEAD
    path: infra/operators
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
