resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

# Disable CRD installation (usually they already exist or are managed separately
installCRDs: true

webhook:
  port: 9443
  resources:
    requests:
      cpu: 50m
      memory: 64Mi

# Setting up the cert-controller (needed to manage webhook certificates
certController:
  create: true
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
